version: 0.0
os: linux
files:
   - source: /
      destination: /home/ec2-user/
hooks:
    BeforeInstall:
        - location: scripts/stop_docker.sh
          timeout: 300
          runas: root
    AfterInstall:
        - location: scripts/authenticate_ecr.sh
          timeout: 300
          runas: root
        - location: scripts/pull_docker_image.sh
          timeout: 300
          runas: root
        - location: scripts/run_docker_image.sh
          timeout: 300
          runas: root



